(function(){
  'use strict';
  if(window.SchatzkarteAITools)return;
  let mode='chat';const $=id=>document.getElementById(id);const ui=v=>window.SKUI?.text(v)||v;const lng=()=>window.SKUI?.lang?.()||'de';
  function setMode(next,label){mode=next||'chat';const chip=$('haiModeChip'),text=$('haiModeText'),quota=$('haiResearchQuota'),sondenQuota=$('haiSondenQuota');if(chip){chip.classList.toggle('active',mode!=='chat');if(text)text.textContent=ui(label||'');}if(quota)quota.hidden=mode!=='research';if(sondenQuota)sondenQuota.hidden=mode!=='sonden_research';if(mode!=='help')$('haiHelp')?.classList.remove('open');}
  function closeMenu(){const menu=$('haiToolsMenu'),button=$('haiToolsButton');menu?.classList.remove('open');button?.setAttribute('aria-expanded','false');}
  function closeMode(){window.SchatzkarteUserFinds?.cancelPending?.();window.__historicalAI?.endResearchMode?.();window.__historicalAI?.endSondenResearchMode?.();setMode('chat');closeMenu();}
  function mount(){
    const form=$('haiForm'),quick=$('haiQuick'),top=$('haiTop'),composer=$('haiComposer');if(!form||!top||!composer||$('haiToolsButton'))return;if(quick)quick.remove();
    const heading=top.querySelector('div');if(heading){const title=heading.querySelector('.hai-title'),sub=heading.querySelector('.hai-sub');if(title)title.textContent='Karten-KI';if(sub)sub.innerHTML='<span class="hai-online-dot"></span> Online';}
    const menuIcon=document.createElement('button');menuIcon.id='haiMenuIcon';menuIcon.type='button';menuIcon.setAttribute('aria-label',ui('KI-Tools öffnen'));menuIcon.textContent='☰';top.insertBefore(menuIcon,top.firstChild);
    const dock=document.createElement('div');dock.id='haiToolsDock';const tools=document.createElement('button');tools.id='haiToolsButton';tools.className='hai-tools-button';tools.type='button';tools.setAttribute('aria-expanded','false');tools.innerHTML='<span>⌘</span> '+ui('Tools öffnen');const quota=document.createElement('span');quota.id='haiResearchQuota';quota.hidden=true;quota.textContent=lng()==='en'?'3 of 3 research requests left':lng()==='cs'?'Zbývají 3 ze 3 průzkumů':lng()==='hu'?'3/3 kutatás maradt':'3 von 3 Recherchen übrig';const sondenQuota=document.createElement('span');sondenQuota.id='haiSondenQuota';sondenQuota.hidden=true;sondenQuota.textContent=lng()==='en'?'3 of 3 detecting-spot searches left':lng()==='cs'?'Zbývají 3 ze 3 průzkumů hledacích míst':lng()==='hu'?'3/3 keresőhely-kutatás maradt':'3 von 3 Sonden-Recherchen übrig';dock.append(tools,quota,sondenQuota);top.parentNode.insertBefore(dock,$('haiMessages'));
    const menu=document.createElement('div');menu.id='haiToolsMenu';menu.className='hai-tools-menu';menu.innerHTML='<div class="hai-tools-heading"><b>KI-Werkzeuge</b><small>Schnellzugriff</small></div><button type="button" data-tool="find"><span>📷</span><div><b>Fund dokumentieren</b><small>Foto analysieren und privat speichern</small></div></button><button type="button" data-tool="place"><span>⌖</span><div><b>Ort zur Karte hinzufügen</b><small>Position wählen und Vorschlag senden</small></div></button><button type="button" data-tool="research"><span>◎</span><div><b>Umgebung recherchieren</b><small>Historische Orte im gewünschten Umkreis suchen</small></div></button><button type="button" data-tool="sonden"><span>⭐</span><div><b>Empfohlene Sondenplätze recherchieren</b><small>Neue allgemeine Suchräume finden · 3 pro Tag</small></div></button>';top.parentNode.insertBefore(menu,$('haiMessages'));
    const chip=document.createElement('div');chip.id='haiModeChip';chip.className='hai-mode-chip';chip.innerHTML='<span id="haiModeText"></span><button id="haiModeClose" type="button" aria-label="'+ui('Modus beenden')+'">×</button>';
    const help=document.createElement('div');help.id='haiHelp';help.className='hai-help';help.innerHTML='<div><strong>'+ui('Karten-KI')+'</strong><button type="button" aria-label="'+ui('Hilfe schließen')+'">×</button></div><p>'+ui('Stelle unten eine normale Frage – oder öffne oben Tools, um einen Fund per Foto zu analysieren.')+'</p>';composer.insertBefore(chip,form);composer.insertBefore(help,form);
    const visibility=$('haiMapVisibility');if(visibility){visibility.classList.add('hai-compact-visibility');menu.appendChild(visibility);}
    const toggleMenu=()=>{const open=!menu.classList.contains('open');menu.classList.toggle('open',open);tools.setAttribute('aria-expanded',String(open));};tools.onclick=toggleMenu;menuIcon.onclick=toggleMenu;$('haiModeClose').onclick=closeMode;help.querySelector('button').onclick=closeMode;
    menu.onclick=e=>{const tool=e.target.closest('[data-tool]:not(:disabled)')?.dataset.tool;if(!tool)return;closeMenu();if(tool==='find'){setMode('personal_find','Fundfoto analysieren');const photo=$('haiPhoto');if(photo)photo.click();else window.SchatzkarteUserFinds?.choosePhoto(false);}else if(tool==='place')window.SchatzkartePlaceSubmission?.open?.();else if(tool==='research'){setMode('research','Umgebung recherchieren');window.__historicalAI?.endSondenResearchMode?.();window.__historicalAI?.beginResearchMode?.();}else if(tool==='sonden'){setMode('sonden_research','Empfohlene Sondenplätze');window.__historicalAI?.endResearchMode?.();window.__historicalAI?.beginSondenResearchMode?.();}};
    document.addEventListener('schatzkarte:research-quota',e=>{const q=$('haiResearchQuota'),d=e?.detail;if(q&&d){const a=Math.max(0,Number(d.remaining)||0),b=Math.max(1,Number(d.limit)||3);q.textContent=lng()==='en'?a+' of '+b+' research requests left':lng()==='cs'?'Zbývá '+a+' z '+b+' průzkumů':lng()==='hu'?a+'/'+b+' kutatás maradt':a+' von '+b+' Recherchen übrig';}});document.addEventListener('schatzkarte:sonden-quota',e=>{const q=$('haiSondenQuota'),d=e?.detail;if(q&&d){const a=Math.max(0,Number(d.remaining)||0),b=Math.max(1,Number(d.limit)||3);q.textContent=lng()==='en'?a+' of '+b+' detecting-spot searches left':lng()==='cs'?'Zbývá '+a+' z '+b+' průzkumů hledacích míst':lng()==='hu'?a+'/'+b+' keresőhely-kutatás maradt':a+' von '+b+' Sonden-Recherchen übrig';}});
    const clear=document.createElement('button');clear.id='haiClear';clear.type='button';clear.title=ui('Chat leeren');clear.setAttribute('aria-label',ui('Chat leeren'));clear.textContent='⌫';top.insertBefore(clear,$('haiClose'));clear.onclick=async()=>{if(await window.SchatzkarteDialog.confirm(ui('Diesen Chatverlauf leeren?'),{title:ui('Chat leeren'),okText:ui('Leeren')}))window.__historicalAI?.clearHistory?.();};
    const ai=window.__historicalAI;if(ai&&Array.isArray(ai.history)&&!ai.history.length){const g=lng()==='en'?'Hello!\nI am your Map AI.\nI can help you find historical places, analyse finds and discover the history around you.\n\nWhat would you like to discover today?':lng()==='cs'?'Ahoj!\nJsem tvoje mapová AI.\nPomohu ti hledat historická místa, analyzovat nálezy a objevovat historii ve tvém okolí.\n\nCo chceš dnes objevit?':lng()==='hu'?'Szia!\nÉn vagyok a Térkép MI-d.\nSegítek történelmi helyeket találni, leleteket elemezni és felfedezni a környék történetét.\n\nMit szeretnél ma felfedezni?':'Hallo!\nIch bin deine Karten-KI.\nIch kann dir helfen, historische Orte zu finden, Funde zu analysieren und die Geschichte deiner Umgebung zu entdecken.\n\nWas möchtest du heute entdecken?';ai.history.push({role:'ai',content:g});}
  }
  function openFromBar(e){const a=window.__historicalAI;if(window.__skMapSearchMode||!a?.enabled||!a.open)return;e?.preventDefault();e?.stopImmediatePropagation();a.open('');}
  function init(){mount();const input=$('skSearchInput');if(input&&!input.__aiDirectOpen){input.__aiDirectOpen=true;input.addEventListener('pointerdown',openFromBar,true);input.addEventListener('focus',openFromBar,true);}window.mapSupabase?.auth?.onAuthStateChange(ev=>{if(ev==='SIGNED_OUT')closeMode();});}
  document.addEventListener('historical-ai-ready',mount);document.addEventListener('user-find-workflow-finished',()=>setMode('chat'));window.SchatzkarteAITools={setMode,closeMode};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
