(function(){
  'use strict';
  if(window.SchatzkarteUserFinds)return;
  const state={pending:null,finds:[],enabled:false,layer:null,markers:new Map(),loading:false};
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(36).slice(2);
  const ai=()=>window.__historicalAI;
  const ui=v=>window.SKUI?.text(v)||v;
  const lng=()=>window.SKUI?.lang?.()||'de';
  function say(role,text,imageDataUrl){if(role!=='user')text=ui(text);const a=ai();if(a?.history)a.history.push({role,content:text,imageDataUrl:imageDataUrl||null});const box=$('haiMessages');if(box){const d=document.createElement('div');d.className='hai-msg '+(role==='user'?'user':'ai');d.innerHTML='<div class="hai-meta">'+ui(role==='user'?'Du':'Historische KI')+'</div>'+esc(text)+(imageDataUrl?'<img class="hai-find-image" src="'+esc(imageDataUrl)+'" alt="'+esc(ui('Foto des Fundes'))+'">':'');box.appendChild(d);box.scrollTop=box.scrollHeight;}}
  function session(){return window.mapSupabase?.auth?.getSession().then(r=>r?.data?.session||null);}
  function ensureLayer(){if(!window.map||!window.L)return null;if(!state.layer)state.layer=window.L.layerGroup();if(state.enabled&&!window.map.hasLayer(state.layer))state.layer.addTo(window.map);return state.layer;}
  function setEnabled(on){state.enabled=!!on;const layer=ensureLayer();if(layer&&window.map){if(state.enabled&&!window.map.hasLayer(layer))layer.addTo(window.map);if(!state.enabled&&window.map.hasLayer(layer))window.map.removeLayer(layer);}syncCategory();if(state.enabled)renderAll();}
  function mountCategory(box){box=box||$('skCategoryList');if(!box||$('skPrivateFindsCategory'))return;const el=document.createElement('div');el.id='skPrivateFindsCategory';el.className='sk-private-finds-category';el.innerHTML='<div class="sk-private-finds-row"><div class="sk-private-finds-icon">📸</div><div class="sk-private-finds-name"><strong>Meine Funde <b id="skPrivateFindsCount">(0)</b></strong><span>Nur für dich sichtbar</span></div><button id="skPrivateFindsToggle" class="sk-private-finds-toggle" type="button" aria-pressed="false" title="Eigene Funde einblenden"><i></i></button></div>';box.prepend(el);$('skPrivateFindsToggle').onclick=()=>setEnabled(!state.enabled);syncCategory();}
  function syncCategory(){const b=$('skPrivateFindsToggle'),c=$('skPrivateFindsCount');if(b){b.classList.toggle('on',state.enabled);b.setAttribute('aria-pressed',String(state.enabled));b.title=ui(state.enabled?'Eigene Funde ausblenden':'Eigene Funde einblenden');}if(c){const l=window.SKUI?.lang?.()||'de',loc={de:'de-DE',en:'en-GB',cs:'cs-CZ',hu:'hu-HU'}[l]||'de-DE';c.textContent='('+state.finds.length.toLocaleString(loc)+')';}}
  async function signed(path){if(!path)return '';const r=await window.mapSupabase.storage.from('user-finds').createSignedUrl(path,3600);return r.error?'':r.data?.signedUrl||'';}
  function formatDate(v){try{const l=window.SKUI?.lang?.()||'de',loc={de:'de-DE',en:'en-GB',cs:'cs-CZ',hu:'hu-HU'}[l]||'de-DE';return new Intl.DateTimeFormat(loc,{dateStyle:'medium',timeStyle:'short'}).format(new Date(v));}catch(_){return String(v||'–');}}
  async function popup(find){const url=await signed(find.main_image_path);return '<div class="user-find-popup">'+(url?'<img src="'+esc(url)+'" alt="Foto des Fundes" onclick="SchatzkarteUserFinds.openImage(this.src)">':'')+'<h3>📸 '+esc(find.title||'Unidentifizierter Gegenstand')+'</h3><p><b>Gefunden:</b> '+esc(formatDate(find.found_at))+'</p><div class="uf-meta"><p><b>KI-Analyse:</b><br>'+esc(find.ai_description||'Keine Analyse vorhanden.')+'</p><p><b>Mögliche Epoche:</b> '+esc(find.possible_period||'Unbekannt')+'</p><p><b>Material:</b> '+esc(find.material||'Unbekannt')+'</p><p><b>KI-Sicherheit:</b> '+esc(find.ai_confidence||'niedrig')+'</p>'+(find.note?'<p><b>Eigene Notiz:</b> '+esc(find.note)+'</p>':'')+'</div><div class="uf-actions"><button onclick="SchatzkarteUserFinds.edit(\''+esc(find.id)+'\')">✏️ Bearbeiten</button><button class="uf-delete" onclick="SchatzkarteUserFinds.remove(\''+esc(find.id)+'\')">🗑️ Löschen</button></div></div>';
  }
  async function addMarker(find){const lat=Number(find.latitude),lon=Number(find.longitude);if(!state.enabled||!Number.isFinite(lat)||!Number.isFinite(lon)||!ensureLayer())return;const old=state.markers.get(find.id);if(old){try{state.layer.removeLayer(old);}catch(_){}state.markers.delete(find.id);}const icon=window.L.divIcon({className:'user-find-marker',html:'<div class="user-find-marker-glyph"><span>📸</span></div>',iconSize:[42,42],iconAnchor:[21,39],popupAnchor:[0,-37]});const marker=window.L.marker([lat,lon],{icon,riseOnHover:true,bubblingMouseEvents:false});marker.bindPopup('<div class="user-find-popup">Fund wird geladen …</div>',{maxWidth:330,closeButton:true});marker.on('click',async()=>{try{const html=await popup(find);marker.bindPopup(html,{maxWidth:330,closeButton:true});marker.openPopup();}catch(e){console.warn('[User finds] popup',e);marker.bindPopup('<div class="user-find-popup">Der Fund konnte nicht geladen werden.</div>',{maxWidth:330,closeButton:true});marker.openPopup();}});marker.addTo(state.layer);state.markers.set(find.id,marker);}
  function renderAll(){if(!ensureLayer())return;state.layer.clearLayers();state.markers.clear();if(state.enabled)state.finds.forEach(addMarker);}
  async function load(){if(state.loading||!window.mapSupabase?.from)return;state.loading=true;try{const s=await session();if(!s){state.finds=[];renderAll();syncCategory();return;}const r=await window.mapSupabase.from('user_finds').select('*').order('found_at',{ascending:false});if(r.error)throw r.error;state.finds=Array.isArray(r.data)?r.data:[];syncCategory();renderAll();}catch(e){console.warn('[User finds] load',e);}finally{state.loading=false;}}
  function dataUrlToBlob(data){const parts=data.split(','),mime=(parts[0].match(/data:([^;]+)/)||[])[1]||'image/jpeg',raw=atob(parts[1]||''),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return new Blob([bytes],{type:mime});}
  function compress(dataUrl){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>{const max=1800,scale=Math.min(1,max/Math.max(image.naturalWidth,image.naturalHeight)),w=Math.max(1,Math.round(image.naturalWidth*scale)),h=Math.max(1,Math.round(image.naturalHeight*scale)),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d',{alpha:false});ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.drawImage(image,0,0,w,h);resolve({dataUrl:canvas.toDataURL('image/jpeg',.82),width:w,height:h});};image.onerror=()=>reject(new Error(ui('Foto konnte nicht verarbeitet werden.')));image.src=dataUrl;});}
  function choosePhotoSource(){return new Promise(resolve=>{let box=$('userFindPhotoChoice');if(box)box.remove();box=document.createElement('div');box.id='userFindPhotoChoice';box.innerHTML='<div class="uf-choice" role="dialog" aria-modal="true" aria-label="Fundfoto auswählen"><strong>Fundfoto hinzufügen</strong><button type="button" data-source="CAMERA">📷 Kamera öffnen</button><button type="button" data-source="PHOTOS">🖼️ Aus Galerie wählen</button><button type="button" data-source="">Abbrechen</button></div>';document.body.appendChild(box);const done=value=>{box.remove();resolve(value||null);};box.onclick=e=>{if(e.target===box)done(null);const source=e.target.closest?.('[data-source]')?.dataset.source;if(source!==undefined)done(source);};});}
  async function choosePhoto(append=false){if(ai()?.busy)return;try{let dataUrl=null;const cam=window.Capacitor?.Plugins?.Camera;if(cam?.getPhoto){const source=await choosePhotoSource();if(!source)return;const p=await cam.getPhoto({quality:88,width:2000,height:2000,allowEditing:false,resultType:'dataUrl',source,saveToGallery:false});dataUrl=p?.dataUrl||null;}else{dataUrl=await webPhoto();}if(!dataUrl)return;const image=await compress(dataUrl);await analyze(image,append);}catch(e){if(!/cancel/i.test(String(e?.message||'')))say('ai','⚠️ '+(e?.message||'Das Foto konnte nicht geöffnet werden.'));}}
  function webPhoto(){return new Promise((resolve,reject)=>{const input=document.createElement('input');input.type='file';input.accept='image/*';input.onchange=()=>{const f=input.files?.[0];if(!f){resolve(null);return;}if(f.size>15000000){reject(new Error(ui('Das Foto ist zu groß.')));return;}const r=new FileReader();r.onload=()=>resolve(typeof r.result==='string'?r.result:null);r.onerror=()=>reject(new Error(ui('Das Foto konnte nicht gelesen werden.')));r.readAsDataURL(f);};input.click();});}
  function analysisText(a){const l=lng(),lab=l==='en'?{o:'Object',m:'Material',d:'Possible dating',ai:'AI analysis',c:'Confidence',more:'Additional helpful photos'}:l==='cs'?{o:'Předmět',m:'Materiál',d:'Možné datování',ai:'AI analýza',c:'Jistota',more:'Další užitečné fotografie'}:l==='hu'?{o:'Tárgy',m:'Anyag',d:'Lehetséges keltezés',ai:'MI-elemzés',c:'Bizonyosság',more:'További hasznos fotók'}:{o:'Gegenstand',m:'Material',d:'Mögliche Datierung',ai:'KI-Analyse',c:'Sicherheit',more:'Weitere hilfreiche Fotos'};let t=lab.o+': '+(a.title||ui('Unidentifizierter Gegenstand'))+'\n\n'+lab.m+': '+(a.material||ui('Unbekannt'))+'\n\n'+lab.d+': '+(a.possible_period||ui('Nicht zuverlässig bestimmbar'))+'\n\n'+lab.ai+':\n'+(a.description||ui('Der Gegenstand lässt sich anhand dieses Fotos nicht zuverlässig identifizieren.'))+'\n\n'+lab.c+': '+(a.confidence||ui('niedrig'));if(a.safety_warning)t+='\n\n⚠️ '+a.safety_warning;if(Array.isArray(a.requested_photos)&&a.requested_photos.length)t+='\n\n'+lab.more+': '+a.requested_photos.join(', ');return t;}
  function showActions(token){const box=$('haiMessages');if(!box)return;const d=document.createElement('div');d.className='hai-find-actions';d.dataset.pendingToken=token;d.innerHTML='<button type="button" class="hai-find-save">📍 In „Meine Funde“ speichern</button><button type="button" class="hai-find-more">📷 Weitere Ansicht hinzufügen</button><button type="button" class="hai-find-discard">Verwerfen</button>';d.onclick=e=>{const button=e.target.closest('button');if(!button)return;if(button.classList.contains('hai-find-save'))saveFromButton(token);if(button.classList.contains('hai-find-more'))addPhoto(token);if(button.classList.contains('hai-find-discard'))discard(token);};box.appendChild(d);box.scrollTop=box.scrollHeight;}
  async function analyze(image,append=false){const a=ai();if(!a?.enabled){say('ai','⚠️ Die Bildanalyse ist nur mit aktivierter KI verfügbar.');return;}a.busy=true;const btn=$('haiPhoto'),send=$('haiSend');if(btn)btn.disabled=true;if(send)send.disabled=true;try{const previous=append&&state.pending&&Date.now()<state.pending.expiresAt?state.pending:null;const images=previous?[...previous.images,image]:[image];state.pending=null;say('user',images.length>1?'Weitere Ansicht zum aktuellen Fund':'Neues Foto zur Fundanalyse',image.dataUrl);say('ai','Bild wird vorsichtig analysiert …');const s=await session();if(!s)throw new Error('Du bist nicht angemeldet.');const endpoint=String(window.MAP_SUPABASE?.url||'').replace(/\/$/,'')+'/functions/v1/analyze-user-find-image';const r=await fetch(endpoint,{method:'POST',headers:{Authorization:'Bearer '+s.access_token,apikey:window.MAP_SUPABASE?.anonKey||'','Content-Type':'application/json'},body:JSON.stringify({images:images.map(x=>x.dataUrl)})});const body=await r.json().catch(()=>({}));if(!r.ok||!body.analysis)throw new Error(body.error||'Die KI-Analyse konnte momentan nicht durchgeführt werden.');const x=body.analysis,token=uid();state.pending={token,title:x.title||'Unidentifizierter Gegenstand',objectType:x.object_type||'unidentified',description:x.description||'Der Gegenstand lässt sich anhand dieses Fotos nicht zuverlässig identifizieren.',possiblePeriod:x.possible_period||'Unbekannt',material:x.material||'Unbekannt',confidence:['niedrig','mittel','hoch'].includes(x.confidence)?x.confidence:'niedrig',images,raw:x,createdAt:new Date().toISOString(),expiresAt:Date.now()+15*60*1000};say('ai',analysisText(x));showActions(token);}catch(e){state.pending=null;say('ai','⚠️ '+(e?.message||'Die KI-Analyse konnte momentan nicht durchgeführt werden.'));}finally{a.busy=false;if(btn)btn.disabled=false;if(send)send.disabled=false;}}
  function validPending(token){return state.pending&&state.pending.token===token&&Date.now()<state.pending.expiresAt;}
  async function saveFromButton(token){if(!validPending(token)){say('ai','Diese Analyse ist nicht mehr aktuell. Bitte verwende den Speichern-Button unter dem neuesten Foto.');return;}document.querySelectorAll('.hai-find-actions button').forEach(b=>b.disabled=true);await savePending();if(!state.pending)document.dispatchEvent(new CustomEvent('user-find-workflow-finished'));}
  function addPhoto(token){if(!validPending(token)){say('ai','Diese Analyse ist nicht mehr aktuell.');return;}choosePhoto(true);}
  function discard(token){if(validPending(token))state.pending=null;const row=document.querySelector('.hai-find-actions[data-pending-token="'+CSS.escape(token)+'"]');if(row)row.innerHTML='<span>Analyse verworfen – nichts wurde gespeichert.</span>';document.dispatchEvent(new CustomEvent('user-find-workflow-finished'));}
  function cancelPending(){state.pending=null;}
  function locate(){return new Promise(resolve=>{if(!window.__schatzkarteGeo){resolve(null);return;}let done=false;const finish=v=>{if(done)return;done=true;resolve(v)};const timer=setTimeout(()=>finish(null),15000);window.__schatzkarteGeo.getCurrentPosition(p=>{clearTimeout(timer);const lat=Number(p?.coords?.latitude),lon=Number(p?.coords?.longitude);finish(Number.isFinite(lat)&&Number.isFinite(lon)?{lat,lon,accuracy:Number(p.coords.accuracy)||null}:null);},()=>{clearTimeout(timer);finish(null);},{enableHighAccuracy:true,maximumAge:0,timeout:12000});});}
  async function savePending(){const p=state.pending;if(!p||Date.now()>p.expiresAt){state.pending=null;say('ai','Diese Fundanalyse ist abgelaufen. Bitte fotografiere den Gegenstand erneut.');return;}const a=ai();a.busy=true;try{const s=await session();if(!s)throw new Error('Du bist nicht angemeldet.');say('ai','Fund wird gespeichert …');const location=await locate();const findId=uid(),now=new Date().toISOString();const payload={id:findId,user_id:s.user.id,title:p.title,latitude:location?.lat??null,longitude:location?.lon??null,location_accuracy:location?.accuracy??null,found_at:now,object_type:p.objectType,possible_period:p.possiblePeriod,material:p.material,ai_description:p.description,ai_confidence:p.confidence,ai_raw_response:p.raw};let insert=await window.mapSupabase.from('user_finds').insert(payload).select('*').single();if(insert.error)throw insert.error;const paths=[];try{const rows=[];for(let i=0;i<p.images.length;i++){const blob=dataUrlToBlob(p.images[i].dataUrl),path=s.user.id+'/'+findId+'/'+uid()+'.jpg';const up=await window.mapSupabase.storage.from('user-finds').upload(path,blob,{contentType:'image/jpeg',upsert:false});if(up.error)throw up.error;paths.push(path);rows.push({find_id:findId,user_id:s.user.id,storage_path:path,mime_type:'image/jpeg',size_bytes:blob.size,width:p.images[i].width,height:p.images[i].height,sort_order:i});}const ir=await window.mapSupabase.from('user_find_images').insert(rows);if(ir.error)throw ir.error;const ur=await window.mapSupabase.from('user_finds').update({main_image_path:paths[0],updated_at:new Date().toISOString()}).eq('id',findId);if(ur.error)throw ur.error;insert.data.main_image_path=paths[0];}catch(e){if(paths.length)await window.mapSupabase.storage.from('user-finds').remove(paths);await window.mapSupabase.from('user_finds').delete().eq('id',findId);throw e;}state.pending=null;state.finds.unshift(insert.data);setEnabled(true);await addMarker(insert.data);syncCategory();if(location&&window.map){say('ai','Gespeichert. Ich habe den Fund an deinem aktuellen Standort zu deinen eigenen Funden hinzugefügt.');$('haiOverlay')?.classList.remove('open');window.map.setView([location.lat,location.lon],17,{animate:true});}else say('ai','Gespeichert, aber aktuell ohne Standort. Der Fund ist in deinen eigenen Funden vorhanden.');}catch(e){say('ai','⚠️ Der Fund wurde nicht gespeichert: '+(e?.message||'Unbekannter Fehler')+'. Du kannst es erneut versuchen.');}finally{a.busy=false;}}
  async function edit(id){const f=state.finds.find(x=>x.id===id);if(!f)return;const values=await window.SchatzkarteDialog.form({title:'Fund bearbeiten',message:'Passe den Titel und deine persönliche Notiz an.',fields:[{label:'Titel',value:f.title||'',maxlength:160},{label:'Eigene Notiz (optional)',value:f.note||'',maxlength:4000,multiline:true}],cancelText:'Abbrechen',okText:'Speichern'});if(!values)return;const title=String(values[0]||'').trim();if(!title){await window.SchatzkarteDialog.alert('Bitte gib einen Titel ein.','Titel fehlt');return;}const note=String(values[1]||'');const r=await window.mapSupabase.from('user_finds').update({title:title.slice(0,160),note:note.slice(0,4000)||null,updated_at:new Date().toISOString()}).eq('id',id).select('*').single();if(r.error){await window.SchatzkarteDialog.alert(ui('Änderung fehlgeschlagen:')+' '+r.error.message);return;}Object.assign(f,r.data);await addMarker(f);window.map?.closePopup?.();}
  async function remove(id){const f=state.finds.find(x=>x.id===id);if(!f)return;const approved=await window.SchatzkarteDialog.confirm('Diesen privaten Fund und seine Fotos wirklich löschen?',{title:'Fund löschen',okText:'Endgültig löschen',danger:true});if(!approved)return;const images=await window.mapSupabase.from('user_find_images').select('storage_path').eq('find_id',id);if(images.error){await window.SchatzkarteDialog.alert('Fund konnte nicht gelöscht werden: '+images.error.message);return;}const paths=(images.data||[]).map(x=>x.storage_path).filter(Boolean);if(paths.length){const sr=await window.mapSupabase.storage.from('user-finds').remove(paths);if(sr.error){await window.SchatzkarteDialog.alert('Fotos konnten nicht gelöscht werden: '+sr.error.message);return;}}const r=await window.mapSupabase.from('user_finds').delete().eq('id',id);if(r.error){await window.SchatzkarteDialog.alert('Fund konnte nicht gelöscht werden: '+r.error.message);return;}const marker=state.markers.get(id);if(marker&&state.layer)state.layer.removeLayer(marker);state.markers.delete(id);state.finds=state.finds.filter(x=>x.id!==id);syncCategory();window.map?.closePopup?.();}
  function openImage(src){let viewer=$('userFindImageViewer');if(!viewer){viewer=document.createElement('div');viewer.id='userFindImageViewer';viewer.innerHTML='<button type="button">×</button><img alt="Fundfoto vergrößert">';document.body.appendChild(viewer);viewer.onclick=e=>{if(e.target===viewer||e.target.tagName==='BUTTON')viewer.classList.remove('open');};}viewer.querySelector('img').src=src;viewer.classList.add('open');}
  function bindAI(){const form=$('haiForm');if(!form||$('haiPhoto'))return;const b=document.createElement('button');b.id='haiPhoto';b.type='button';b.title=ui('Neuen Fund fotografieren oder Foto auswählen');b.setAttribute('aria-label',b.title);b.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8.2 5.5 9.4 3.8h5.2l1.2 1.7H19a2 2 0 0 1 2 2v10.2a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7.5a2 2 0 0 1 2-2h3.2Z"/><circle cx="12" cy="12.5" r="4"/></svg>';form.insertBefore(b,$('haiInput'));b.onclick=()=>choosePhoto(false);form.addEventListener('submit',()=>{state.pending=null;},true);}
  function init(){mountCategory();bindAI();let tries=0;const timer=setInterval(()=>{mountCategory();bindAI();if(window.map){clearInterval(timer);ensureLayer();load();}else if(tries++>100)clearInterval(timer);},100);window.mapSupabase?.auth?.onAuthStateChange((event)=>setTimeout(()=>{if(event==='SIGNED_OUT'){state.pending=null;state.finds=[];renderAll();syncCategory();}else if(['SIGNED_IN','INITIAL_SESSION','TOKEN_REFRESHED'].includes(event))load();},0));}
  window.SchatzkarteUserFinds={mountCategory,load,setEnabled,choosePhoto,saveFromButton,addPhoto,discard,cancelPending,edit,remove,openImage};
  document.addEventListener('historical-ai-ready',bindAI);
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
